- pipeline: "Production"
  events:
  - type: "PULL_REQUEST"
    branches:
    - "master"
  fail_on_prepare_env_warning: true
  resources: "NANO"
  actions:
  - action: "cd package && zip -r ../deployment-package.zip ."
    type: "BUILD"
    docker_image_name: "library/python"
    docker_image_tag: "3.13"
    execute_commands:
    - "mkdir -p package"
    - "pip install -r requirements.txt -t package/"
    - "cp app.py secrets_manager.py package/"
    - "cd package && zip -r ../deployment-package.zip ."
    - ""
    cached_dirs:
    - "/root/.cache/pip"
    shell: "BASH"
  - action: "Deploy function costanzaapi"
    type: "AWS_LAMBDA_DEPLOY"
    region: "us-east-1"
    integration: "Amazon_Web_Services"
    deployment_excludes:
    - ".git"
    function_name: "costanzaapi"
