# name: Build and Push to ECR

# on:
#   push:
#     branches:
#       - master 
# jobs:
#   build-and-push:
#     name: Build and Push Docker Image to ECR
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#     - name: Log in to Amazon ECR
#       id: login-ecr
#       uses: aws-actions/amazon-ecr-login@v2
#       with:
#         region: us-east-1
    
#     - name: Build, Tag, and Push
#       env:
#         REPOSITORY_URI: 265842400786.dkr.ecr.us-east-1.amazonaws.com/costanza-fast-api-backend
#         IMAGE_TAG: latest
#       run: |
#         docker build -t $REPOSITORY_URI:$IMAGE_TAG .
#         docker push $REPOSITORY_URI:$IMAGE_TAG


# name: Build and Push to ECR

on:
    push:
        branches:
            - master 
jobs:
    build-and-push:
        name: Build and Push Docker Image to ECR
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Log in to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build, Tag, and Push
              env:
                  REPOSITORY_URI: 265842400786.dkr.ecr.us-east-1.amazonaws.com/costanza-fast-api-backend
                  IMAGE_TAG: latest
              run: |
                  docker build -t $REPOSITORY_URI:$IMAGE_TAG .
                  docker push $REPOSITORY_URI:$IMAGE_TAG