name: Build and Push to ECR

on:
  push:
    branches:
      - master  # Trigger on pushes to the 'master' branch

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  build-and-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::265842400786:role/costanza-gha
        # role-to-assume: arn:aws:iam::265842400786:role/gha-new
      
        aws-region: us-east-1 # AWS Region for the resources

        

        
    # Step 3: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Step 4: Build, Tag, and Push Docker Image
    - name: Build, Tag, and Push Docker Image
      env:
        REPOSITORY_URI: 265842400786.dkr.ecr.us-east-1.amazonaws.com/costanza-fast-api-backend
        IMAGE_TAG: latest
      run: |
        docker build -t $REPOSITORY_URI:$IMAGE_TAG .
        docker push $REPOSITORY_URI:$IMAGE_TAG
